default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: 127.0.0.1
  username: root # MySQLインストール時のユーザー名に合わせてください
  password: # 自分のMySQLのパスワードに合わせる
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inst_app2_development

test:
  <<: *default
  database: inst_app2_test
